apiVersion: v1
kind: Service
metadata:
  name: sentinel
  namespace: infra
  labels:
    k8s-app: sentinel
spec:
  clusterIP: None
  ports:
  - port: 26379
    targetPort: client
    name: sentinel
  selector:
    k8s-app: sentinel
