apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: sentinel
  namespace: infra
  labels:
    k8s-app: sentinel
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  serviceName: sentinel
  replicas: 3
  selector:
    matchLabels:
      k8s-app: sentinel
  template:
    metadata:
      labels:
        k8s-app: sentinel
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - image: gn00023040/kubernetes-redis:4.0.6
        name: sentinel
        env:
        - name: SENTINEL
          value: "true"
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - containerPort: 26379
          name: client
        livenessProbe:
          exec:
            command:
            - redis-cli
            - -p 
            - "26379"
            - ping
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - redis-cli
            - -p
            - "26379"
            - ping
          initialDelaySeconds: 5
          timeoutSeconds: 1
