apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: twemproxy
  labels:
    k8s-app: twemproxy
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: twemproxy
  template:
    metadata:
      labels:
        k8s-app: twemproxy
    spec:
      containers:
      - name: twemproxy
        image: gn00023040/kubernetes-twemproxy:v0.4.1
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        ports:
        - containerPort: 6379
          name: redis
          protocol: TCP
        volumeMounts:
        - name: config-volume
          mountPath: /etc/twemproxy/conf
      volumes:
      - name: config-volume
        configMap:
          name: twemproxy-config
