apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: twemproxy
  labels:
    k8s-app: twemproxy
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: twemproxy
  template:
    metadata:
      labels:
        k8s-app: twemproxy
    spec:
      containers:
      - name: twemproxy
        image: gn00023040/kubernetes-twemproxy:0.4.1
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - name: config-volume
          mountPath: /etc/twemproxy
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          timeoutSeconds: 1
      - name: nutcracker-web
        image: gn00023040/kubernetes-nutcracker-web:0.0.14
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        ports:
        - containerPort: 9292
          name: web
        volumeMounts:
        - name: config-volume
          mountPath: /etc/twemproxy
        livenessProbe:
          failureThreshold: 8
          httpGet:
            host: 127.0.0.1
            path: /
            port: 9292
            scheme: HTTP
          initialDelaySeconds: 15
          timeoutSeconds: 15
      volumes:
      - name: config-volume
        configMap:
          name: twemproxy-config
