apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: infra
  labels:
    k8s-app: redis
spec:
  clusterIP: None
  ports:
  - port: 6379
    targetPort: client
    name: redis
  selector:
    k8s-app: redis
